### ISSUE TITLE
Unable to delete media that doesn't have a referenced entities file field.

### ISSUE THREAD

**Issue by jordandukart** [Islandora/documentation#1628]
When creating a media that doesn't utilize an entity reference based file field the `Delete media and files` action will whitescreen:

```
Error: Call to undefined method Drupal\Core\Field\FieldItemList::referencedEntities() in Drupal\islandora\Plugin\Action\DeleteMediaAndFile->execute() (line 103 of /opt/www/drupal/modules/contrib/islandora/src/Plugin/Action/DeleteMediaAndFile.php)

#0 /opt/www/drupal/core/lib/Drupal/Core/Action/ActionBase.php(22): Drupal\islandora\Plugin\Action\DeleteMediaAndFile->execute(Object(Drupal\media\Entity\Media))
#1 /opt/www/drupal/core/modules/system/src/Entity/Action.php(129): Drupal\Core\Action\ActionBase->executeMultiple(Array)
#2 /opt/www/drupal/core/modules/views/src/Plugin/views/field/BulkForm.php(435): Drupal\system\Entity\Action->execute(Array)
#3 /opt/www/drupal/core/modules/views/src/Form/ViewsFormMainForm.php(185): Drupal\views\Plugin\views\field\BulkForm->viewsFormSubmit(Array, Object(Drupal\Core\Form\FormState))
#4 /opt/www/drupal/core/modules/views/src/Form/ViewsForm.php(187): Drupal\views\Form\ViewsFormMainForm->submitForm(Array, Object(Drupal\Core\Form\FormState))
...
```

This is due to other media types like core's `Remote Video` referencing URLs in the field as opposed to entities proper. See if the thing is actually an `EntityReferenceFieldItemList` before trying to use it as such.

**Comment by jordandukart** [comment]
Perhaps not an issue or manifesting differently with ~~the multi file merge~~ confirm form changes. Will need to verify against HEAD.

**Comment by ajstanley** [comment]
@jordandukart  There is no call to referencedEntities() on line 103 of the `8.x-1.x `branch.  Any chance you're on `main`?

**Comment by jordandukart** [comment]
Ya pre multi-file code, will be a bit before I can verify this on head.

**Comment by ajstanley** [comment]
It was changed pre-multifile when @qadan put in the confirmation form. (Mid August)

**Comment by jordandukart** [comment]
Updated my original comment to accurately reflect @ajstanley
